name: Static Analysis
on: [push, pull_request]
permissions:
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Get dependencies
      run: >-
        sudo apt-get update &&
        sudo apt-get install
        gcc
        libegl1-mesa-dev
        libgl1-mesa-dev
        libgles2-mesa-dev
        libx11-dev
        xorg-dev
        xvfb
        language-pack-en

    - name: Set environment variable LANG
      run: export LANG=en_EN.UTF-8

    - name: Install analysis tools
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go install github.com/mattn/goveralls@latest
        go install lucor.dev/lian@latest

    - name: Vet
      run: go vet ./...

    - name: Goimports
      run: test -z "$(goimports -e -d . | tee /dev/stderr)"

    - name: Gocyclo
      run: gocyclo -over 30 .

    - name: Staticcheck
      run: staticcheck ./...

